// Generated by Supabase CLI - do not edit by hand.
// Regenerate with:
//   SUPABASE_ACCESS_TOKEN=<project-scoped-token> npx supabase gen types typescript --project-id ilybqnoqgcvyxlicwsjz > src/lib/supabase/database.types.ts (minus this header)

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5";
  };
  public: {
    Tables: {
      admin_users: {
        Row: {
          created_at: string;
          user_id: string;
        };
        Insert: {
          created_at?: string;
          user_id: string;
        };
        Update: {
          created_at?: string;
          user_id?: string;
        };
        Relationships: [];
      };
      event_types: {
        Row: {
          created_at: string;
          id: string;
          label: string;
          slug: string;
          sort_order: number;
        };
        Insert: {
          created_at?: string;
          id?: string;
          label: string;
          slug: string;
          sort_order?: number;
        };
        Update: {
          created_at?: string;
          id?: string;
          label?: string;
          slug?: string;
          sort_order?: number;
        };
        Relationships: [];
      };
      faqs: {
        Row: {
          answer: string;
          created_at: string;
          highlight: boolean;
          id: string;
          question: string;
          slug: string;
          sort_order: number;
          updated_at: string;
        };
        Insert: {
          answer: string;
          created_at?: string;
          highlight?: boolean;
          id?: string;
          question: string;
          slug: string;
          sort_order?: number;
          updated_at?: string;
        };
        Update: {
          answer?: string;
          created_at?: string;
          highlight?: boolean;
          id?: string;
          question?: string;
          slug?: string;
          sort_order?: number;
          updated_at?: string;
        };
        Relationships: [];
      };
      gallery_items: {
        Row: {
          caption: string;
          created_at: string;
          highlight: boolean;
          id: string;
          image_alt: string;
          image_key: string | null;
          image_src: string;
          slug: string;
          sort_order: number;
          updated_at: string;
        };
        Insert: {
          caption?: string;
          created_at?: string;
          highlight?: boolean;
          id?: string;
          image_alt: string;
          image_key?: string | null;
          image_src?: string;
          slug: string;
          sort_order?: number;
          updated_at?: string;
        };
        Update: {
          caption?: string;
          created_at?: string;
          highlight?: boolean;
          id?: string;
          image_alt?: string;
          image_key?: string | null;
          image_src?: string;
          slug?: string;
          sort_order?: number;
          updated_at?: string;
        };
        Relationships: [];
      };
      inquiries: {
        Row: {
          created_at: string;
          email: string;
          event_date: string;
          event_type: string | null;
          guests: string | null;
          id: string;
          message: string | null;
          mobile: string | null;
          name: string;
          photobooth: string | null;
          venue: string | null;
        };
        Insert: {
          created_at?: string;
          email: string;
          event_date: string;
          event_type?: string | null;
          guests?: string | null;
          id?: string;
          message?: string | null;
          mobile?: string | null;
          name: string;
          photobooth?: string | null;
          venue?: string | null;
        };
        Update: {
          created_at?: string;
          email?: string;
          event_date?: string;
          event_type?: string | null;
          guests?: string | null;
          id?: string;
          message?: string | null;
          mobile?: string | null;
          name?: string;
          photobooth?: string | null;
          venue?: string | null;
        };
        Relationships: [];
      };
      packages: {
        Row: {
          badge_type: Database["public"]["Enums"]["package_badge"];
          created_at: string;
          custom_badge: string;
          duration_label: string;
          highlight: boolean;
          id: string;
          image_alt: string;
          image_key: string | null;
          image_src: string;
          inclusions: string[];
          name: string;
          price_label: string;
          slug: string;
          sort_order: number;
          summary: string;
          updated_at: string;
        };
        Insert: {
          badge_type?: Database["public"]["Enums"]["package_badge"];
          created_at?: string;
          custom_badge?: string;
          duration_label: string;
          highlight?: boolean;
          id?: string;
          image_alt?: string;
          image_key?: string | null;
          image_src?: string;
          inclusions?: string[];
          name: string;
          price_label: string;
          slug: string;
          sort_order?: number;
          summary: string;
          updated_at?: string;
        };
        Update: {
          badge_type?: Database["public"]["Enums"]["package_badge"];
          created_at?: string;
          custom_badge?: string;
          duration_label?: string;
          highlight?: boolean;
          id?: string;
          image_alt?: string;
          image_key?: string | null;
          image_src?: string;
          inclusions?: string[];
          name?: string;
          price_label?: string;
          slug?: string;
          sort_order?: number;
          summary?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      page_contents: {
        Row: {
          content: Json;
          page_key: string;
          updated_at: string;
        };
        Insert: {
          content?: Json;
          page_key: string;
          updated_at?: string;
        };
        Update: {
          content?: Json;
          page_key?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      page_seo: {
        Row: {
          canonical_url: string;
          keywords: string;
          nofollow: boolean;
          noindex: boolean;
          og_description: string;
          og_image_alt: string;
          og_image_key: string | null;
          og_image_src: string;
          og_title: string;
          page_key: string;
          seo_description: string;
          seo_title: string;
          updated_at: string;
        };
        Insert: {
          canonical_url?: string;
          keywords?: string;
          nofollow?: boolean;
          noindex?: boolean;
          og_description?: string;
          og_image_alt?: string;
          og_image_key?: string | null;
          og_image_src?: string;
          og_title?: string;
          page_key: string;
          seo_description: string;
          seo_title: string;
          updated_at?: string;
        };
        Update: {
          canonical_url?: string;
          keywords?: string;
          nofollow?: boolean;
          noindex?: boolean;
          og_description?: string;
          og_image_alt?: string;
          og_image_key?: string | null;
          og_image_src?: string;
          og_title?: string;
          page_key?: string;
          seo_description?: string;
          seo_title?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      services: {
        Row: {
          badge_type: Database["public"]["Enums"]["service_badge"];
          created_at: string;
          custom_badge: string;
          highlight: boolean;
          highlights: string[];
          icon: string | null;
          id: string;
          image_alt: string;
          image_key: string | null;
          image_src: string;
          name: string;
          slug: string;
          sort_order: number;
          summary: string;
          tagline: string | null;
          updated_at: string;
        };
        Insert: {
          badge_type?: Database["public"]["Enums"]["service_badge"];
          created_at?: string;
          custom_badge?: string;
          highlight?: boolean;
          highlights?: string[];
          icon?: string | null;
          id?: string;
          image_alt?: string;
          image_key?: string | null;
          image_src?: string;
          name: string;
          slug: string;
          sort_order?: number;
          summary: string;
          tagline?: string | null;
          updated_at?: string;
        };
        Update: {
          badge_type?: Database["public"]["Enums"]["service_badge"];
          created_at?: string;
          custom_badge?: string;
          highlight?: boolean;
          highlights?: string[];
          icon?: string | null;
          id?: string;
          image_alt?: string;
          image_key?: string | null;
          image_src?: string;
          name?: string;
          slug?: string;
          sort_order?: number;
          summary?: string;
          tagline?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      testimonials: {
        Row: {
          created_at: string;
          event_type: string;
          id: string;
          name: string;
          quote: string;
          rating: number | null;
          slug: string;
          sort_order: number;
          updated_at: string;
        };
        Insert: {
          created_at?: string;
          event_type: string;
          id?: string;
          name: string;
          quote: string;
          rating?: number | null;
          slug: string;
          sort_order?: number;
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          event_type?: string;
          id?: string;
          name?: string;
          quote?: string;
          rating?: number | null;
          slug?: string;
          sort_order?: number;
          updated_at?: string;
        };
        Relationships: [];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      is_admin: { Args: never; Returns: boolean };
    };
    Enums: {
      package_badge: "none" | "basic" | "most-popular" | "best-value" | "custom";
      service_badge: "basic" | "most-popular" | "best-value" | "custom";
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">;

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">];

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R;
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] & DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R;
      }
      ? R
      : never
    : never;

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    keyof DefaultSchema["Tables"] | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I;
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I;
      }
      ? I
      : never
    : never;

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    keyof DefaultSchema["Tables"] | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U;
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U;
      }
      ? U
      : never
    : never;

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    keyof DefaultSchema["Enums"] | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never;

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    keyof DefaultSchema["CompositeTypes"] | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never;

export const Constants = {
  public: {
    Enums: {
      package_badge: ["none", "basic", "most-popular", "best-value", "custom"],
      service_badge: ["basic", "most-popular", "best-value", "custom"],
    },
  },
} as const;
